#ifndef FIRMWARE_CAN_NODE_CONFIG_H
#define FIRMWARE_CAN_NODE_CONFIG_H

#define CAN_NODE_BUFFER_SIZE        256
#define CAN_NODE_MAX_CB_PAIRS       8

#define CAN_NODE_MAX_PACKET_SIZE    8

#endif //FIRMWARE_CAN_NODE_CONFIG_H
