#ifndef __RCAN_BUS_GPIO_H
#define __RCAN_BUS_GPIO_H


#define FDCAN1_TX_GPIO_PORT      GPIOB
#define FDCAN1_RX_GPIO_PORT      GPIOB
#define FDCAN1_TX_GPIO_PIN       GPIO_PIN_8
#define FDCAN1_RX_GPIO_PIN       GPIO_PIN_9


#define FDCAN1_TX_GPIO_PORT      GPIOB
#define FDCAN1_RX_GPIO_PORT      GPIOB
#define FDCAN1_TX_GPIO_PIN       GPIO_PIN_8
#define FDCAN1_RX_GPIO_PIN       GPIO_PIN_9


#endif